blank_issues_enabled: false
contact_links:
  - name: CPM Documentation
    url: https://github.com/Qchains/CPM-cli/tree/main/docs
    about: Read the documentation for help with CPM
  - name: Security Vulnerability
    url: https://github.com/Qchains/CPM-cli/security/advisories/new
    about: Report a security vulnerability privately