/*
 * File:  [Õf±û.h
 * Description: Header file for  [Õf±û library
 * Generated by CPM init
 */

#ifndef  [ÕF±û_H
#define  [ÕF±û_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Print a hello message from the  [Õf±û library
 */
void  [Õf±û_hello(void);

/**
 * Get the major version number
 * @return Major version number
 */
int  [Õf±û_version_major(void);

/**
 * Get the minor version number
 * @return Minor version number
 */
int  [Õf±û_version_minor(void);

#ifdef __cplusplus
}
#endif

#endif /*  [ÕF±û_H */
