/*
 * File:  K¥Ü_ø.h
 * Description: Header file for  K¥Ü_ø library
 * Generated by CPM init
 */

#ifndef  K¥Ü_ø_H
#define  K¥Ü_ø_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Print a hello message from the  K¥Ü_ø library
 */
void  K¥Ü_ø_hello(void);

/**
 * Get the major version number
 * @return Major version number
 */
int  K¥Ü_ø_version_major(void);

/**
 * Get the minor version number
 * @return Minor version number
 */
int  K¥Ü_ø_version_minor(void);

#ifdef __cplusplus
}
#endif

#endif /*  K¥Ü_ø_H */
