/*
 * File:  «ŽZµþ.h
 * Description: Header file for  «ŽZµþ library
 * Generated by CPM init
 */

#ifndef  «ŽZµþ_H
#define  «ŽZµþ_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Print a hello message from the  «ŽZµþ library
 */
void  «ŽZµþ_hello(void);

/**
 * Get the major version number
 * @return Major version number
 */
int  «ŽZµþ_version_major(void);

/**
 * Get the minor version number
 * @return Minor version number
 */
int  «ŽZµþ_version_minor(void);

#ifdef __cplusplus
}
#endif

#endif /*  «ŽZµþ_H */
