/*
 * File: main.c
 * Description: Example usage of  [Õf±û library
 * Generated by CPM init
 */

#include " [Õf±û.h"
#include <stdio.h>

int main(void) {
    printf("Example program for  [Õf±û\n");
    printf("Version: %d.%d\n",  [Õf±û_version_major(),  [Õf±û_version_minor());
    
     [Õf±û_hello();
    
    return 0;
}
