/*
 * File: main.c
 * Description: Example usage of  K¥Ü_ø library
 * Generated by CPM init
 */

#include " K¥Ü_ø.h"
#include <stdio.h>

int main(void) {
    printf("Example program for  K¥Ü_ø\n");
    printf("Version: %d.%d\n",  K¥Ü_ø_version_major(),  K¥Ü_ø_version_minor());
    
     K¥Ü_ø_hello();
    
    return 0;
}
