/*
 * File: main.c
 * Description: Example usage of  «ŽZµþ library
 * Generated by CPM init
 */

#include " «ŽZµþ.h"
#include <stdio.h>

int main(void) {
    printf("Example program for  «ŽZµþ\n");
    printf("Version: %d.%d\n",  «ŽZµþ_version_major(),  «ŽZµþ_version_minor());
    
     «ŽZµþ_hello();
    
    return 0;
}
