/*
 * File:  [Õf±û.c
 * Description: Main implementation for  [Õf±û library
 * Generated by CPM init
 */

#include " [Õf±û.h"
#include <stdio.h>
#include <stdlib.h>

void  [Õf±û_hello(void) {
    printf("Hello from  [Õf±û!\n");
}

int  [Õf±û_version_major(void) {
    return 1;
}

int  [Õf±û_version_minor(void) {
    return 0;
}
