/*
 * File:  K¥Ü_ø.c
 * Description: Main implementation for  K¥Ü_ø library
 * Generated by CPM init
 */

#include " K¥Ü_ø.h"
#include <stdio.h>
#include <stdlib.h>

void  K¥Ü_ø_hello(void) {
    printf("Hello from  K¥Ü_ø!\n");
}

int  K¥Ü_ø_version_major(void) {
    return 1;
}

int  K¥Ü_ø_version_minor(void) {
    return 0;
}
