/*
 * File:  «ŽZµþ.c
 * Description: Main implementation for  «ŽZµþ library
 * Generated by CPM init
 */

#include " «ŽZµþ.h"
#include <stdio.h>
#include <stdlib.h>

void  «ŽZµþ_hello(void) {
    printf("Hello from  «ŽZµþ!\n");
}

int  «ŽZµþ_version_major(void) {
    return 1;
}

int  «ŽZµþ_version_minor(void) {
    return 0;
}
